apiVersion: v2
description: pgAdmin4 is a web based administration tool for PostgreSQL database
name: pgadmin4
version: 1.50.0
appVersion: "9.8"
keywords:
  - pgadmin
  - postgres
  - database
  - sql
