apiVersion: v1
kind: ConfigMap
metadata:
  name: kiwi-settings
data:
  settings.py: |
    import os

    # Add the authentication backends
    AUTHENTICATION_BACKENDS = (
        'social_core.backends.azuread.AzureADOAuth2',
        'django.contrib.auth.backends.ModelBackend',
    )

    # Configure the social auth settings
    SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = os.getenv('AZUREAD_CLIENT_ID')
    SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = os.getenv('AZUREAD_CLIENT_SECRET')
    SOCIAL_AUTH_AZUREAD_OAUTH2_TENANT_ID = os.getenv('AZUREAD_TENANT_ID')

    # Add the login redirect URL
    LOGIN_REDIRECT_URL = '/'
    LOGOUT_REDIRECT_URL = '/accounts/login/'

    # Add the social auth pipeline
    SOCIAL_AUTH_PIPELINE = (
        'social_core.pipeline.social_auth.social_details',
        'social_core.pipeline.social_auth.social_uid',
        'social_core.pipeline.social_auth.auth_allowed',
        'social_core.pipeline.social_auth.social_user',
        'social_core.pipeline.user.get_username',
        'social_core.pipeline.user.create_user',
        'social_core.pipeline.social_auth.associate_user',
        'social_core.pipeline.social_auth.load_extra_data',
        'social_core.pipeline.user.user_details',
    )